### ISSUE TITLE
Installation problem: No local packages found for "entrypoints"

### ISSUE THREAD

**Issue by DSLituiev** [jupyter/jupyter#150] opened 2016-05-05 21:27 UTC
I am trying to install Jupyter on CentOS 6.7, python3.4 and getting this error. Where can one get this `entrypoints` package? Can find none on google.
```
Processing dependencies for jupyter==1.0.0
Searching for entrypoints
Reading https://pypi.python.org/simple/entrypoints/
No local packages or download links found for entrypoints
error: Could not find suitable distribution for Requirement.parse('entrypoints')
```

Same error with `easy_install3 jupyter` or `easy_install3 -U git://github.com/jupyter/jupyter`

**Comment by takluyver** [comment] 2016-05-05 21:33
I think that means you have a very old version of pip. Try upgrading pip
before installing jupyter, by running pip install --upgrade pip.

**Comment by DSLituiev** [comment] 2016-05-05 21:44
I am using easy_install, not pip.

Unfortunately on this system [pip does not work](
http://stackoverflow.com/questions/36806315/pip-target-directory-on-centos6-with-scl
).

**Comment by willingc** [comment] 2016-05-05 21:49
Have you tried to install pip:
```
sudo yum python-pip
```

Detailed instructions on installing pip with CentOS 6 are found [here](https://packaging.python.org/en/latest/install_requirements_linux/#centos-rhel)

**Comment by DSLituiev** [comment] 2016-05-05 23:22
No. Pip is not a solution:

1) pip is installed, but I could not make it use proper path. I tried all means to no avail. Now it just erases everything if I try to run it.
2) the machine has several pythons (2.6, 3.3, 3.4, 2.7) under SCL.
3) I am not an admin.

**Comment by willingc** [comment] 2016-05-06 01:08
@DSLituiev Perhaps using easy_install and the entrypoints source would work in your scenario. After downloading the entrypoints source as a zip file (button on right hand side), [repo url](https://github.com/takluyver/entrypoints):

<img width="1022" alt="screen shot 2016-05-05 at 6 02 19 pm" src="https://cloud.githubusercontent.com/assets/2680980/15061570/c6580d2a-12eb-11e6-9503-11afea21b177.png">

Following example 6 in the easy_install docs [here](http://pythonhosted.org/setuptools/easy_install.html#downloading-and-installing-a-package). Do the following:
1. extract the contents of the zip file
2. At the root of the extracted contents directory, enter ``easy_install .``

Hope this helps.

**Comment by takluyver** [comment] 2016-05-06 07:44
Easy install will not work. That tool really needs to die. Try using pip to
install just entrypoints, with a -t flag to specify the target directory,
and then, if you must, use easy_install to install the other stuff.

**Comment by takluyver** [comment] 2016-05-06 07:55
I'm looking into the Stackoverflow question.

**Comment by DSLituiev** [comment] 2016-05-06 21:25
It does not work. Entrypoints has no `setup.py`

**Comment by takluyver** [comment] 2016-05-14 15:57
Closing as @DSLituiev found a way to get pip working (from discussion on SO).

**Closed by takluyver** 2016-05-14 15:57 UTC

**Comment by ajmazurie** [comment] 2016-06-23 19:36
To add to the discussion, the problem is not due to a too-old version of pip; I got today the very same error message with version 8.1.2.

**Comment by jakirkham** [comment] 2016-08-08 20:33
Also running into this issue with Python 2.7, 3.4, and 3.5 using the latest `pip` (8.1.2) and latest `setuptools` (25.1.6). @ajmazurie's workaround of installing `entrypoints` worked for me as well. Given the suggestion is use more recent versions of `pip` and `setuptools`, which we are already doing, am wondering if there is something more going on with this issue.

**Comment by takluyver** [comment] 2016-08-08 20:53
I'm not sure how that happens. I've just created a blank environment, with those same versions of pip and setuptools, run `pip install jupyter`, and sure enough:

```
Collecting entrypoints (from nbconvert->jupyter)
  Using cached entrypoints-0.2.2-py2.py3-none-any.whl
```

**Comment by jakirkham** [comment] 2016-08-08 20:54
I don't know either. It seems to be happening for me on Travis CI almost exclusively. My attempts to reproduce it locally failed repeatedly. 😕 Can point you to the logs if you would like to take a closer look.

**Comment by takluyver** [comment] 2016-08-08 21:43
Sure, point away. I've got some sleeping to do, but I'll look tomorrow in
my time zone.

**Comment by jakirkham** [comment] 2016-08-08 22:04
Sounds good. Put PR ( https://github.com/paulgb/runipy/pull/125 ) together to show the `backports.shutil_get_terminal_size` error and `entrypoints` error. In both cases, the first 3 CI builds in the matrix are of interest. All 3 of these use `pip` to install everything.

**Comment by takluyver** [comment] 2016-08-10 10:30
As Min pointed out in paulgb/runipy#126, the solution in that case is to use `pip install .`.

Other people reading this: at this point you should *never* be running `python setup.py install` directly, unless some weird special circumstances require it. `pip install .` does the same thing with a modern, wheel-aware toolchain. And it's fewer characters to type.
