### ISSUE TITLE
kernel stops when plotting large array

### ISSUE THREAD

**Issue by sbenthall** [jupyter/jupyter#135] opened 2016-04-06 17:01 UTC
I am getting a consistent error when trying to plot a large array in a Jupyter notebook.

When I try to plot the array, I get an error message in the UI saying the kernel has stopped and will restart automatically.

In my console where I have started the NotebookApp, I get the following error message

```
[3754:3754:0406/093509:ERROR:logging.h(813)] Failed to call method: org.freedesktop.DBus.ObjectManager.GetManagedObjects: object_path= /: org.freedesktop.DBus.Error.UnknownMethod: Method "GetManagedObjects" with signature "" on interface "org.freedesktop.DBus.ObjectManager" doesn't exist
```

Not sure where the best place is to file this ticket. Is a different repo better?

**Comment by takluyver** [comment] 2016-04-06 17:08
What kind of plotting are you trying to do? Is it possible that it's running out of memory? Does the same operation work outside of a notebook?

I think the DBus error is likely to be a symptom rather than a cause: we don't do anything with DBus.

**Comment by tacaswell** [comment] 2016-04-08 04:04
How large? I wonder if the issue is that mpl is locking up the process and the heart-beat is failing.

**Comment by sbenthall** [comment] 2016-04-11 19:11
`plt.loglog(np.ravel(m.todense())`

where m is a 

```
<78617x78617 sparse matrix of type '<class 'numpy.int64'>'
	with 304492 stored elements in Compressed Sparse Row format>
```

:)

**Comment by tacaswell** [comment] 2016-04-12 00:24
That is going to result in ~3-4 copies of a 48GB array (once for todense, maybe once for ravel, once copying in the y data, and once for the implicit x data).  I am not super surprised that your kernel is falling over.

**Comment by ivanov** [comment] 2023-11-17 21:06
7 years later, closing this out. Thanks everyone, and 
Happy hacking! :bowtie:

**Closed by ivanov** 2023-11-17 21:06 UTC
