### ISSUE TITLE
Jupyter cant find Python after a fresh Anaconda installation

### ISSUE THREAD

**Issue by albahnsen** [jupyter/jupyter#181] opened 2016-07-05 22:22 UTC
After a fresh install I got this warning in the Jupyter console, and the error trying to load a notebook. 
![image](https://cloud.githubusercontent.com/assets/3617224/16601756/8d3b12ee-42d4-11e6-8c50-0df88fab29ed.png)

If I open the Anaconda Prompt, ipython and python run perfectly
![image](https://cloud.githubusercontent.com/assets/3617224/16601786/c8bc8b18-42d4-11e6-845b-b082c331aff6.png)

I'm at the Uni computers with Windows 7 SP1 (and admin access)

**Comment by takluyver** [comment] 2016-07-05 22:53
What error did you get trying to load a notebook? Nothing in the console looks very problematic.

**Comment by albahnsen** [comment] 2016-07-05 23:10
When I click new notebook it did not connect to python. It says dead kernel.

**Comment by takluyver** [comment] 2016-07-06 09:46
Your fresh install seems to be finding some extensions from a previous install `nb_conda_kernels`, `nb_anacondacloud`, `nbpresent`...

There may be a problem with one of those. Try disabling them and see if it works.

**Comment by albahnsen** [comment] 2016-07-06 13:42
There was no previous installation of Jupyter or Python

**Comment by damianavila** [comment] 2016-07-08 13:34
> When I click new notebook it did not connect to python. It says dead kernel.

When you select `Python[Root]` and creates a new notebook... it says dead kernel? Or you have a previous notebook and you try to open it and see that message...

Btw, this seems something specific about nb_conda_kernels... I will open an issue there: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/35 to continue the discussion and this one can be closed.

**Comment by bollwyvl** [comment] 2016-08-01 16:39
@albahnsen   We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! 

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by damianavila** [comment] 2016-08-01 17:49
Can you close this one @takluyver, thanks!

**Closed** 2016-08-01 19:47 UTC
